// <auto-generated />
using AnimalCollection.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalCollection.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220119182219_animal_animaltypes_merge")]
    partial class animal_animaltypes_merge
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("AnimalCollection.Entities.Animal", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AnimalTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("AnimalTypeID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AnimalTypeID = 1,
                            Name = "Dog"
                        },
                        new
                        {
                            ID = 2,
                            AnimalTypeID = 2,
                            Name = "Raven"
                        },
                        new
                        {
                            ID = 3,
                            AnimalTypeID = 3,
                            Name = "Salmon"
                        },
                        new
                        {
                            ID = 4,
                            AnimalTypeID = 4,
                            Name = "Bearded Dragon"
                        },
                        new
                        {
                            ID = 5,
                            AnimalTypeID = 5,
                            Name = "Ladybird"
                        },
                        new
                        {
                            ID = 6,
                            AnimalTypeID = 6,
                            Name = "Frog"
                        });
                });

            modelBuilder.Entity("AnimalCollection.Entities.AnimalType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.ToTable("AnimalTypes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Mammal"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Bird"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Fish"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Reptile"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Insect"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Amphibian"
                        });
                });

            modelBuilder.Entity("AnimalCollection.Entities.Animal", b =>
                {
                    b.HasOne("AnimalCollection.Entities.AnimalType", "AnimalType")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalType");
                });

            modelBuilder.Entity("AnimalCollection.Entities.AnimalType", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
